[package]
name = "artificecore-logging"
version = "0.1.0"
edition = "2021"
authors = ["Detrivos"]
description = "Logging module for ArtificeCore - compatible with standard Rust log crate"

[lib]
name = "logging"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.40"
log = "0.4.27"
