[package]
name = "artifice-engine"
version = "0.0.0"
edition = "2021"
authors = ["Spencer Yascolt"]
description = "The core libraries for the artifice-engine"

[lib]
name = "artifice_engine"
path = "src/lib.rs"

[dependencies]
glfw = "0.59.0"
gl = "0.14.0"
